# Generated by Django 5.2.10 on 2026-02-04 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authapp', '0005_alter_profile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WorkerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_Pay', models.IntegerField()),
                ('job_description', models.TextField()),
                ('experience', models.IntegerField()),
                ('hourly_rate', models.IntegerField()),
                ('skills', models.ManyToManyField(related_name='worker_skills', to='workerapp.skill')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='worker_profile', to='authapp.profile')),
            ],
        ),
    ]
