# Generated by Django 5.2.10 on 2026-04-11 08:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workerapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workerprofile",
            name="base_Pay",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(99999),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="workerprofile",
            name="experience",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(999),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="workerprofile",
            name="hourly_rate",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(9999),
                ]
            ),
        ),
    ]
