upstream backend_api {
    server backend:8000;
}

upstream chat_service {
    server chat-service:8001;
}

server {
    listen 80;

    # 1. Standard API and Admin traffic
    location / {
        proxy_pass http://backend_api;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # 2. WebSocket traffic (The Chat)
    location /ws/ {
        proxy_pass http://chat_service;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;
    }
}