# Generated by Django 6.0.1 on 2026-01-21 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='hustlrusers',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='hustlrusers',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
