# Generated by Django 6.0.1 on 2026-01-21 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_alter_hustlrusers_managers_alter_hustlrusers_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hustlrusers',
            name='username',
        ),
    ]
