# Generated by Django 5.2.10 on 2026-03-28 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authapp", "0005_alter_profile_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="fcm_token",
            field=models.TextField(blank=True, null=True),
        ),
    ]
