# Generated by Django 5.2.10 on 2026-03-25 13:32

import cloudinary_storage.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "employerapp",
            "0006_jobrequest_contract_hourly_rate_jobrequest_end_time_and_more",
        ),
        ("workerapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("city", models.CharField(max_length=100)),
                (
                    "job_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        storage=cloudinary_storage.storage.MediaCloudinaryStorage(),
                        upload_to="job_posts/",
                    ),
                ),
                (
                    "employer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_hiring_posts",
                        to="employerapp.employerprofile",
                    ),
                ),
                (
                    "worker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recieve_job_posts",
                        to="workerapp.workerprofile",
                    ),
                ),
            ],
        ),
    ]
