# Generated by Django 5.2.10 on 2026-03-25 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employerapp", "0007_jobpost"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobpost",
            name="worker",
        ),
    ]
