# Generated by Django 5.2.10 on 2026-03-26 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employerapp", "0008_remove_jobpost_worker"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobrequest",
            name="job_post",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="applications",
                to="employerapp.jobpost",
            ),
        ),
    ]
