# Generated by Django 5.2.10 on 2026-03-27 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employerapp", "0009_jobrequest_job_post"),
        ("workerapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobpost",
            name="required_skills",
            field=models.ManyToManyField(
                blank=True, related_name="job_posts", to="workerapp.skill"
            ),
        ),
    ]
