# Generated by Django 5.2.10 on 2026-03-28 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employerapp", "0010_jobpost_required_skills"),
        ("workerapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobrequest",
            name="expiry_notification_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name="jobrequest",
            index=models.Index(
                fields=["created_at", "status"], name="employerapp_created_89321d_idx"
            ),
        ),
    ]
