# Generated by Django 5.2.10 on 2026-03-30 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employerapp", "0011_jobrequest_expiry_notification_sent_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobpost",
            name="job_image",
            field=models.ImageField(blank=True, null=True, upload_to="job_posts/"),
        ),
    ]
