# Generated by Django 5.2.10 on 2026-04-01 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employerapp", "0012_alter_jobpost_job_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobbilling",
            name="is_paid",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="jobbilling",
            name="paid_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="jobbilling",
            name="razorpay_order_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="jobbilling",
            name="razorpay_payment_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
