# Generated by Django 5.2.10 on 2026-04-11 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employerapp", "0013_jobbilling_is_paid_jobbilling_paid_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobbilling",
            name="bill_image",
            field=models.ImageField(blank=True, null=True, upload_to="job_bills/"),
        ),
        migrations.AlterField(
            model_name="jobpost",
            name="title",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="jobrequest",
            name="project_image",
            field=models.ImageField(blank=True, null=True, upload_to="job_requests/"),
        ),
    ]
