# Generated by Django 5.2.10 on 2026-04-11 09:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "employerapp",
            "0014_alter_jobbilling_bill_image_alter_jobpost_title_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobrequest",
            name="estimated_hours",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0.01),
                    django.core.validators.MaxValueValidator(9999),
                ],
            ),
        ),
    ]
