# Generated by Django 5.2.10 on 2026-04-11 09:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employerapp", "0015_alter_jobrequest_estimated_hours"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobbilling",
            name="material_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(99999),
                ],
            ),
        ),
    ]
