# Generated by Django 5.2.10 on 2026-04-24 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employerapp", "0016_alter_jobbilling_material_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobrequest",
            name="is_employer_initiated",
            field=models.BooleanField(default=True),
        ),
    ]
